with
    CombinedData
    AS
    (

                    select 'BWL' as schemaName, Rtrim(concat(item.imfgr, item.icolor, item.ipatt)) as itemNumber,
    [IMFGR],
    [ICOLOR],
    [IPATT],
    [ISHADE],
    [ILOT#],
    [ICOLDE],
    [INAME],
    [INAME2],
    [IABC],
    [IDISCD],
    [ISITM#],
    [ICCTR],
    [IUNDER],
    [IUNDGL],
    [IMINCD],
    [IODAYS],
    [IPATH],
    [IFILL3],
    [IXTRCD],
    [IUMSUP],
    [IISOT#],
    [IIXREF],
    [IQBGRP],
    [IFRTCL],
    [IPRTUM],
    [IUMSAL],
    [ICLAST],
    [ICLAS1],
    [ICLAS2],
    [ICLAS3],
    [IPATDE],
    [ISPCL#],
    [IDELIV],
    [IPOL1],
    [IPOL2],
    [IPOL3],
    [IFIL2],
    [IMIN],
    [ITAX],
    [IQBMUL],
    [ILPODT],
    [ILRCTD],
    [ISEQ#],
    [IINIT],
    [IINVEN],
    [ICOMPO],
    [IPRCCD],
    [IPACCD],
    [ICSTCD],
    [IUM2],
    [IQTYLM],
    [IQTYLY],
    [IUMPRC],
    [IDFTGP],
    [ILIST],
    [IUNITS],
    [IUNITC],
    [ISUPP#],
    [IPRODL],
    [ICOMM1],
    [IWEARC],
    [IWIDTH],
    [IREMNA],
    [ICOMLV],
    [ILCHDT],
    [IFLAGS],
    [IDEL],
    [MFGR#],
    [MNAME],
    [LID],
    [LMFGR#],
    [LPROD#],
    [LNAME],
    [LUNITS],
    [SUPP#],
    [SNAME],
    [SPOL1],
    [SPOL2],
    [SPOL3],
    [UPACCD],
    [UM#@1],
    [UM#@2],
    [UM#@3],
    [UM#@4],
    [UM#@5],
    [UM#@6],
    [UM1@1],
    [UM1@2],
    [UM1@3],
    [UM1@4],
    [UM1@5],
    [UM1@6],
    [UM2@1],
    [UM2@2],
    [UM2@3],
    [UM2@4],
    [UM2@5],
    [UM2@6],
    [UDESC],
    [UFILL1],
    [UPRTIN],
    [ULCHDT],
    [UDEL],
    [$PRCCD],
    [$LIST#],
    [$ENDUS],
    [$UNITS],
    [$DESC],
    1 as priority

            from dancik_bwl.item as item
                left join dancik_bwl.mfgr as mfgr on imfgr = mfgr#
                left join dancik_bwl.prodline as prodline on imfgr = lmfgr# and iprodl = lprod#
                left join dancik_bwl.supplier as supplier on isupp# = supp#
                left join dancik_bwl.package as package on ipaccd = upaccd
                left join dancik_bwl.price as price on iprccd = [$PRCCD] and [$LIST#] = 'LP'
            where idiscd = 0
                and icompo in ('S', 'R')
                and iixref = ''

        UNION ALL

            select 'WAN' as schemaName, rtrim(concat(item.imfgr, item.icolor, item.ipatt)) as itemNumber,
    [IMFGR],
    [ICOLOR],
    [IPATT],
    [ISHADE],
    [ILOT#],
    [ICOLDE],
    [INAME],
    [INAME2],
    [IABC],
    [IDISCD],
    [ISITM#],
    [ICCTR],
    [IUNDER],
    [IUNDGL],
    [IMINCD],
    [IODAYS],
    [IPATH],
    [IFILL3],
    [IXTRCD],
    [IUMSUP],
    [IISOT#],
    [IIXREF],
    [IQBGRP],
    [IFRTCL],
    [IPRTUM],
    [IUMSAL],
    [ICLAST],
    [ICLAS1],
    [ICLAS2],
    [ICLAS3],
    [IPATDE],
    [ISPCL#],
    [IDELIV],
    [IPOL1],
    [IPOL2],
    [IPOL3],
    [IFIL2],
    [IMIN],
    [ITAX],
    [IQBMUL],
    [ILPODT],
    [ILRCTD],
    [ISEQ#],
    [IINIT],
    [IINVEN],
    [ICOMPO],
    [IPRCCD],
    [IPACCD],
    [ICSTCD],
    [IUM2],
    [IQTYLM],
    [IQTYLY],
    [IUMPRC],
    [IDFTGP],
    [ILIST],
    [IUNITS],
    [IUNITC],
    [ISUPP#],
    [IPRODL],
    [ICOMM1],
    [IWEARC],
    [IWIDTH],
    [IREMNA],
    [ICOMLV],
    [ILCHDT],
    [IFLAGS],
    [IDEL],
    [MFGR#],
    [MNAME],
    [LID],
    [LMFGR#],
    [LPROD#],
    [LNAME],
    [LUNITS],
    [SUPP#],
    [SNAME],
    [SPOL1],
    [SPOL2],
    [SPOL3],
    [UPACCD],
    [UM#@1],
    [UM#@2],
    [UM#@3],
    [UM#@4],
    [UM#@5],
    [UM#@6],
    [UM1@1],
    [UM1@2],
    [UM1@3],
    [UM1@4],
    [UM1@5],
    [UM1@6],
    [UM2@1],
    [UM2@2],
    [UM2@3],
    [UM2@4],
    [UM2@5],
    [UM2@6],
    [UDESC],
    [UFILL1],
    [UPRTIN],
    [ULCHDT],
    [UDEL],
    [$PRCCD],
    [$LIST#],
    [$ENDUS],
    [$UNITS],
    [$DESC],
    2 as priority
            from dancik_wan.item as item
                left join dancik_wan.mfgr as mfgr on imfgr = mfgr#
                left join dancik_wan.prodline as prodline on imfgr = lmfgr# and iprodl = lprod#
                left join dancik_wan.supplier as supplier on isupp# = supp#
                left join dancik_wan.package as package on ipaccd = upaccd
                left join dancik_wan.price as price on iprccd = [$PRCCD] and [$LIST#] = 'LP'
            where idiscd = 0
                and icompo in ('S', 'R')
                and iixref = ''

    )


SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY itemNumber ORDER BY priority) AS rn
    FROM CombinedData
) AS Ranked
WHERE rn = 1
ORDER BY IMFGR, iprodl, ICOLOR, IPATT;